### PR TITLE
Use innerText instead of selenium call

### LINKED ISSUE #30: getText doesn't seem to always works
While trying to track a weird problem, it seemed stem from `getText()` returning an empty string, even when I can see the correct element is being selected and the expected content is show when I use `getOuterHtml()` or `getHtml()`.

There isa major difference in the implementation between those:
https://github.com/minkphp/webdriver-classic-driver/blob/9567c6e77c2b89dcdc5a5f567ce826c1a831de1f/src/WebdriverClassicDriver.php#L297
vs:
https://github.com/minkphp/webdriver-classic-driver/blob/9567c6e77c2b89dcdc5a5f567ce826c1a831de1f/src/WebdriverClassicDriver.php#L304

I was able to solve my problem by using `return $this->getElementDomProperty($this->findElement($xpath), 'textContent');`.

I have a feeling the original implementation was the same in all three cases, so now I'm wondering which case is the really correct one, when the dedicated cases seems to misbehave.

### PR DESCRIPTION
**Pull request by uuf6429**
Fixes #30

### CODE REVIEW

**Comment by uuf6429** [comment]
@aik099 the remaining failures were already happening before. I made a new issue for that: #33

**Review by aik099 — APPROVED** [review]
Looks good.

**Comment by aik099** [comment]
You might be interested in porting https://github.com/minkphp/MinkSelenium2Driver/pull/328 fix to this driver (in this or separate PR).

**Comment by uuf6429** [comment]
Done

**Comment by aik099** [comment]
Merging. Thanks @uuf6429 .

**Pull request merged**
