### PR TITLE
Add driver factory and extension

### LINKED ISSUE #15: Connect this driver to the "Behat\MinkExtension" project
Currently, there is no way to use this driver in the Behat, because there is no corresponding driver in the https://github.com/Behat/MinkExtension/tree/master/src/Behat/MinkExtension/ServiceContainer/Driver .

The driver key would be `webdriver-classic` instead of `selenium2`. The current Selenium2 driver could be used as a starting point.

@uuf6429 , please submit a PR to that repo.

### PR DESCRIPTION
**Pull request by uuf6429**
Closes #15.

### CODE REVIEW

**Comment by aik099** [comment]
@uuf6429 , Adding the `behat/mink-extension` as a driver dependency assumes, that the only way to use the driver is through the Mink+Behat combo. This is incorrect.

Mink moved away from the `Behat` GitHub organization into its own `minkphp` GitHub organization a long time ago. I guess the reason for that was that Mink can be used on its own and not only through the Behat. The existence of these projects proves it:

* https://github.com/qa-tools/qa-tools/
* https://github.com/minkphp/phpunit-mink/

That might indirectly answer your question in https://github.com/minkphp/webdriver-classic-driver/issues/15#issuecomment-1963472897 as well.

**Review by aik099 — CHANGES_REQUESTED** [review]
The Behat needs Mink, not the other way around. In this point of view the PR needs to be made into the https://github.com/FriendsOfBehat/MinkExtension as we've discussed in the associated issue.

**Comment by uuf6429** [comment]
> The Behat needs Mink, not the other way around. In this point of view the PR needs to be made into the https://github.com/FriendsOfBehat/MinkExtension as we've discussed in the associated issue.

That feels like yet another problem of the `behat/mink-extension` package. As [I said earlier](https://github.com/minkphp/webdriver-classic-driver/issues/15#issuecomment-1963472897), the factories shouldn't be behat(/mink-extension)-specific.

What maybe makes sense in this case is to remove `behat/mink-extension` from `require`, leave the FriendsOfBehat one in `require-dev` and also add it to `suggests`. What do you think?

**Comment by stof** [comment]
This does not belong here. This should go inside the MinkExtension repository (or in a separate extension, but as this is an official Mink driver, it can go in the main MinkExtension).

Mink itself should not depend on Behat extensions.

**Pull request closed without merging**
